version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd_storage
    ports:
      - "2379:2379"
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/etcd-data
    restart: unless-stopped
    networks:
      - kaizen-network

  load-balancer:
    image: kaizenlb:1.0
    container_name: kaizenlb_service
    depends_on:
      - etcd
    ports:
      - "8080:8080"
    environment:
      - ETCD_HOST=etcd
    restart: unless-stopped
    networks:
      - kaizen-network

volumes:
  etcd-data:

networks:
  kaizen-network:
    driver: bridge
